gtnh.settings.blowdryerTag = 0.2.2

modName = AppliedExpansion
modId = appliedexpansion
modGroup = com.misaka2592.appliedexpansion
useModGroupForPublishing = true
autoUpdateBuildScript = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

developmentEnvironmentUserName = Developer
enableModernJavaSyntax = jabel
enableGenericInjection = true

generateGradleTokenClass = com.misaka2592.appliedexpansion.Tags
gradleTokenVersion = VERSION

usesMixins = true
usesMixinDebug = false
mixinsPackage = mixins
containsMixinsAndOrCoreModOnly = false
usesShadowedDependencies = false

includeWellKnownRepositories = true
usesMavenPublishing = false

ae2Version = rv3-beta-977-GTNH

org.gradle.configuration-cache = true
org.gradle.parallel = true
